package com.gihansgamage.gpamaster.utils

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.os.Environment
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream
import java.io.PrintWriter
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Handles export of GPA results to PDF, TXT, and CSV formats.
 * Files are saved to the app's external files directory and shared via FileProvider.
 */
object ExportHelper {

    data class SemesterData(
        val year: Int,
        val semesterNumber: Int,
        val gpa: Double,
        val totalCredits: Double,
        val subjects: List<SubjectData>
    )

    data class SubjectData(
        val name: String,
        val credits: Double,
        val grade: String,
        val gradePoints: Double
    )

    private fun timestamp(): String =
        SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(Date())

    private fun getExportDir(context: Context): File {
        val dir = File(context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS), "GpaMaster")
        dir.mkdirs()
        return dir
    }

    // ── TXT ──────────────────────────────────────────────────────────────────

    fun exportTxt(
        context: Context,
        userName: String,
        overallGpa: Double,
        weightedGpa: Double?,
        scale: String,
        totalCredits: Double,
        semesters: List<SemesterData>
    ): File {
        val file = File(getExportDir(context), "GpaReport_${timestamp()}.txt")
        PrintWriter(FileOutputStream(file)).use { pw ->
            val sep = "=".repeat(48)
            val dash = "-".repeat(48)

            pw.println(sep)
            pw.println("  GPA MASTER — ACADEMIC REPORT")
            pw.println("  Student : $userName")
            pw.println("  Scale   : $scale")
            pw.println("  Date    : ${SimpleDateFormat("dd MMM yyyy", Locale.getDefault()).format(Date())}")
            pw.println(sep)
            pw.println()
            pw.println("  Overall GPA   : ${String.format("%.2f", overallGpa)}")
            if (weightedGpa != null) {
                pw.println("  Weighted GPA  : ${String.format("%.2f", weightedGpa)}")
            }
            pw.println("  Total Credits : ${totalCredits.toInt()}")
            pw.println("  Subjects      : ${semesters.sumOf { it.subjects.size }}")
            pw.println()

            for (sem in semesters) {
                pw.println(sep)
                pw.println("  Year ${sem.year}  •  Semester ${sem.semesterNumber}")
                pw.println("  Semester GPA: ${String.format("%.2f", sem.gpa)}   Credits: ${sem.totalCredits.toInt()}")
                pw.println(dash)
                pw.println("  %-30s %7s %6s %8s".format("Subject", "Credits", "Grade", "Points"))
                pw.println(dash)
                for (s in sem.subjects) {
                    pw.println("  %-30s %7s %6s %8s".format(
                        s.name.take(30), s.credits.toInt(), s.grade, String.format("%.2f", s.gradePoints)
                    ))
                }
                pw.println()
            }

            pw.println(sep)
            pw.println("  Generated by GPA Master")
            pw.println(sep)
        }
        return file
    }

    // ── CSV ───────────────────────────────────────────────────────────────────

    fun exportCsv(
        context: Context,
        userName: String,
        overallGpa: Double,
        weightedGpa: Double?,
        scale: String,
        totalCredits: Double,
        semesters: List<SemesterData>
    ): File {
        val file = File(getExportDir(context), "GpaReport_${timestamp()}.csv")
        PrintWriter(FileOutputStream(file)).use { pw ->
            // Header meta
            pw.println("GPA Master Academic Report")
            pw.println("Student,${userName}")
            pw.println("Scale,${scale}")
            pw.println("Date,${SimpleDateFormat("dd MMM yyyy", Locale.getDefault()).format(Date())}")
            pw.println("Overall GPA,${String.format("%.2f", overallGpa)}")
            if (weightedGpa != null) {
                pw.println("Weighted GPA,${String.format("%.2f", weightedGpa)}")
            }
            pw.println("Total Credits,${totalCredits.toInt()}")
            pw.println()

            // Column headers
            pw.println("Year,Semester,Semester GPA,Subject,Credits,Grade,Grade Points")

            for (sem in semesters) {
                if (sem.subjects.isEmpty()) continue
                for ((i, s) in sem.subjects.withIndex()) {
                    val yearStr = if (i == 0) sem.year.toString() else ""
                    val semStr = if (i == 0) sem.semesterNumber.toString() else ""
                    val gpaStr = if (i == 0) String.format("%.2f", sem.gpa) else ""
                    
                    pw.println("$yearStr,$semStr,$gpaStr,\"${s.name}\",${s.credits.toInt()},${s.grade},${String.format("%.2f", s.gradePoints)}")
                }
            }
            pw.println()
            pw.println("Generated by GPA Master App")
        }
        return file
    }

    // ── PDF ───────────────────────────────────────────────────────────────────

    fun exportPdf(
        context: Context,
        userName: String,
        overallGpa: Double,
        weightedGpa: Double?,
        scale: String,
        totalCredits: Double,
        semesters: List<SemesterData>
    ): File {
        val file = File(getExportDir(context), "GpaReport_${timestamp()}.pdf")

        val pageWidth = 595   // A4 width in points
        val pageHeight = 842  // A4 height in points
        val margin = 40f
        val contentWidth = pageWidth - margin * 2

        val paintTitle = Paint().apply { textSize = 22f; isFakeBoldText = true; color = Color.parseColor("#009688") }
        val paintHeader = Paint().apply { textSize = 11f; isFakeBoldText = true; color = Color.WHITE }
        val paintMeta = Paint().apply { textSize = 11f; color = Color.parseColor("#455A64") }
        val paintRow = Paint().apply { textSize = 10f; color = Color.parseColor("#263238") }
        val paintRowBold = Paint().apply { textSize = 10f; isFakeBoldText = true; color = Color.parseColor("#009688") }
        val paintLine = Paint().apply { style = Paint.Style.STROKE; strokeWidth = 0.5f; color = Color.parseColor("#E0E0E0") }
        val paintHeaderBg = Paint().apply { color = Color.parseColor("#009688") }
        val paintAltBg = Paint().apply { color = Color.parseColor("#F4FBFB") }
        val paintFooterLeft = Paint().apply { textSize = 9f; color = Color.parseColor("#9E9E9E"); textAlign = Paint.Align.LEFT }
        val paintFooterRight = Paint().apply { textSize = 9f; color = Color.parseColor("#9E9E9E"); textAlign = Paint.Align.RIGHT }
        val paintThickLine = Paint().apply { style = Paint.Style.STROKE; strokeWidth = 1.5f; color = Color.parseColor("#009688") }

        val document = PdfDocument()
        var pageNum = 1
        var page = document.startPage(PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNum).create())
        var canvas = page.canvas
        var y = margin

        fun drawFooter(c: Canvas) {
            c.drawLine(margin, pageHeight - 35f, pageWidth - margin, pageHeight - 35f, paintLine)
            c.drawText("Generated by GPA Master — Download the app to track your grades professionally.", margin, pageHeight - 20f, paintFooterLeft)
            c.drawText("Page $pageNum", pageWidth - margin, pageHeight - 20f, paintFooterRight)
        }

        fun newPage() {
            drawFooter(canvas)
            document.finishPage(page)
            pageNum++
            page = document.startPage(PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNum).create())
            canvas = page.canvas
            y = margin
        }

        fun checkY(needed: Float) { if (y + needed > pageHeight - margin - 35f) newPage() }

        // --- Header Section ---
        
        // Draw Logo (using standard app icon)
        try {
            val resId = context.resources.getIdentifier("ic_launcher", "mipmap", context.packageName)
            if (resId != 0) {
                val drawable = androidx.core.content.ContextCompat.getDrawable(context, resId)
                if (drawable != null) {
                    val bitmap = android.graphics.Bitmap.createBitmap(48, 48, android.graphics.Bitmap.Config.ARGB_8888)
                    val canvasBitmap = android.graphics.Canvas(bitmap)
                    drawable.setBounds(0, 0, canvasBitmap.width, canvasBitmap.height)
                    drawable.draw(canvasBitmap)
                    canvas.drawBitmap(bitmap, margin, y, null)
                }
            }
        } catch (e: Exception) {
            // Ignore if logo fails
        }
        
        canvas.drawText("GPA MASTER", margin + 60f, y + 20f, paintTitle)
        canvas.drawText("Official Academic Report", margin + 60f, y + 38f, paintMeta)

        y += 55f
        
        // Header separator line
        canvas.drawLine(margin, y, pageWidth - margin, y, paintThickLine)
        y += 15f
        
        // Summary block
        val summaryBg = Paint().apply { color = Color.parseColor("#E0F2F1") }
        canvas.drawRoundRect(margin, y, pageWidth - margin, y + 45f, 6f, 6f, summaryBg)
        
        val smPaint = Paint().apply { textSize = 11f; isFakeBoldText = true; color = Color.parseColor("#00695C") }
        canvas.drawText("Student: $userName", margin + 12f, y + 16f, smPaint)
        canvas.drawText("Date: ${SimpleDateFormat("dd MMM yyyy", Locale.getDefault()).format(Date())}", margin + 12f, y + 32f, paintMeta)
        
        canvas.drawText("Overall GPA: ${String.format("%.2f", overallGpa)}", margin + 200f, y + 16f, smPaint)
        if (weightedGpa != null) {
            canvas.drawText("Weighted GPA: ${String.format("%.2f", weightedGpa)}", margin + 200f, y + 32f, smPaint)
        }
        canvas.drawText("Scale: $scale", margin + 350f, y + 16f, paintMeta)
        
        canvas.drawText("Credits: ${totalCredits.toInt()}", margin + 350f, y + 32f, smPaint)
        
        y += 65f

        // --- Table Headers ---
        // Widths: Year(35), Sem(35), SemGPA(45), Subject(230), Cr(40), Grade(50), Pts(50) = 485
        // Adjusted for 515 contentWidth: Y(40), S(40), GPA(50), Subj(235), Cr(45), Gr(50), Pts(55)
        val colX = floatArrayOf(
            margin,
            margin + 40f,
            margin + 80f,
            margin + 130f,
            margin + 365f,
            margin + 410f,
            margin + 460f
        )
        
        fun drawTableHeaders() {
            canvas.drawRoundRect(margin, y, pageWidth - margin, y + 20f, 4f, 4f, paintHeaderBg)
            val hY = y + 14f
            canvas.drawText("Year", colX[0] + 4, hY, paintHeader)
            canvas.drawText("Sem", colX[1] + 4, hY, paintHeader)
            canvas.drawText("GPA", colX[2] + 4, hY, paintHeader)
            canvas.drawText("Subject", colX[3] + 4, hY, paintHeader)
            canvas.drawText("Cr", colX[4] + 4, hY, paintHeader)
            canvas.drawText("Grade", colX[5] + 4, hY, paintHeader)
            canvas.drawText("Points", colX[6] + 4, hY, paintHeader)
            y += 20f
        }

        drawTableHeaders()

        // --- Table Rows ---
        var isAltRow = false
        for (sem in semesters) {
            if (sem.subjects.isEmpty()) continue
            
            for ((i, s) in sem.subjects.withIndex()) {
                checkY(20f)
                
                // Draw background for alternate rows
                if (isAltRow) {
                    canvas.drawRect(margin, y, pageWidth - margin, y + 18f, paintAltBg)
                }
                
                val rY = y + 13f
                
                // Draw Sem group columns only on first row
                if (i == 0) {
                    canvas.drawText(sem.year.toString(), colX[0] + 4, rY, paintRowBold)
                    canvas.drawText(sem.semesterNumber.toString(), colX[1] + 4, rY, paintRowBold)
                    canvas.drawText(String.format("%.2f", sem.gpa), colX[2] + 4, rY, paintRowBold)
                }
                
                // Subject details
                canvas.drawText(s.name.take(45), colX[3] + 4, rY, paintRow)
                canvas.drawText(s.credits.toInt().toString(), colX[4] + 4, rY, paintRow)
                canvas.drawText(s.grade, colX[5] + 4, rY, paintRowBold)
                canvas.drawText(String.format("%.2f", s.gradePoints), colX[6] + 4, rY, paintRow)
                
                // Grid lines (vertical)
                for (cx in colX) canvas.drawLine(cx, y, cx, y + 18f, paintLine)
                canvas.drawLine(pageWidth - margin, y, pageWidth - margin, y + 18f, paintLine)
                
                // Grid line (horizontal)
                canvas.drawLine(margin, y + 18f, pageWidth - margin, y + 18f, paintLine)
                
                y += 18f
                isAltRow = !isAltRow
            }
            
            // Add a slightly thicker separator line after each semester
            val thickLine = Paint(paintLine).apply { strokeWidth = 1.5f; color = Color.parseColor("#B2DFDB") }
            canvas.drawLine(margin, y, pageWidth - margin, y, thickLine)
        }

        drawFooter(canvas)
        document.finishPage(page)
        
        FileOutputStream(file).use { document.writeTo(it) }
        document.close()
        return file
    }

    // ── Share ─────────────────────────────────────────────────────────────────

    fun shareFile(context: Context, file: File) {
        val uri: Uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.provider",
            file
        )
        val mime = when (file.extension.lowercase()) {
            "pdf" -> "application/pdf"
            "csv" -> "text/csv"
            else  -> "text/plain"
        }
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = mime
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, "Share ${file.name}"))
    }

    // ── CSV Template ──────────────────────────────────────────────────────────

    fun generateCsvTemplate(context: Context, userName: String, scale: String): File {
        val file = File(getExportDir(context), "GpaMaster_Template.csv")
        PrintWriter(FileOutputStream(file)).use { pw ->
            // Header meta
            pw.println("GPA Master Academic Report")
            pw.println("Student,${userName}")
            pw.println("Scale,${scale}")
            pw.println("Date,${SimpleDateFormat("dd MMM yyyy", Locale.getDefault()).format(Date())}")
            pw.println("Overall GPA,0.00")
            pw.println("Total Credits,0")
            pw.println()

            // Column headers
            pw.println("Year,Semester,Semester GPA,Subject,Credits,Grade,Grade Points")
            
            // Example row
            pw.println("1,1,0.00,\"Example Subject 1\",3,A,4.00")
            pw.println(",,,\"Example Subject 2\",2,B+,3.30")
            
            pw.println()
            pw.println("Generated by GPA Master App")
        }
        return file
    }
}
