package com.gihansgamage.gpamaster.utils

import android.content.Context
import android.net.Uri
import com.gihansgamage.gpamaster.models.Subject
import java.io.BufferedReader
import java.io.InputStreamReader

object ImportHelper {

    fun importCsv(context: Context, uri: Uri): Result<Int> {
        return try {
            val inputStream = context.contentResolver.openInputStream(uri)
                ?: throw Exception("Could not open file")
            
            val reader = BufferedReader(InputStreamReader(inputStream))
            
            var studentName: String? = null
            var scale: String? = null
            var isParsingSubjects = false
            
            var currentYear = 1
            var currentSemester = 1
            var importedCount = 0
            
            val semesterManager = SemesterManager(context)
            val prefsHelper = PrefsHelper(context)
            
            reader.useLines { lines ->
                for (line in lines) {
                    if (line.isBlank()) continue
                    
                    if (!isParsingSubjects) {
                        if (line.startsWith("Student,")) {
                            studentName = line.substringAfter("Student,").trim()
                        } else if (line.startsWith("Scale,")) {
                            scale = line.substringAfter("Scale,").trim()
                        } else if (line.startsWith("Year,Semester,Semester GPA,Subject,Credits,Grade,Grade Points")) {
                            isParsingSubjects = true
                            // If name and scale are found, update preferences
                            if (!studentName.isNullOrBlank()) {
                                prefsHelper.saveUserName(studentName!!)
                            }
                            if (!scale.isNullOrBlank()) {
                                prefsHelper.saveScale(scale!!)
                            }
                        }
                    } else {
                        if (line.startsWith("Generated by GPA Master App")) {
                            break // End of file
                        }
                        
                        // Parse subject row
                        // Format: Year,Semester,Semester GPA,"Subject Name",Credits,Grade,Grade Points
                        // Note: Subject name is in quotes
                        
                        // Simple CSV parser for this specific format
                        val tokens = parseCsvLine(line)
                        if (tokens.size >= 6) {
                            val yearStr = tokens[0].trim()
                            val semStr = tokens[1].trim()
                            // index 2 is Sem GPA, which we ignore
                            val subjectName = tokens[3].trim()
                            val creditsStr = tokens[4].trim()
                            val grade = tokens[5].trim()
                            
                            if (yearStr.isNotEmpty()) {
                                currentYear = yearStr.toIntOrNull() ?: currentYear
                            }
                            if (semStr.isNotEmpty()) {
                                currentSemester = semStr.toIntOrNull() ?: currentSemester
                            }
                            
                            val credits = creditsStr.toDoubleOrNull() ?: continue
                            
                            // Get or create the semester
                            val semester = semesterManager.getOrCreateSemester(currentYear, currentSemester)
                            
                            // Check if subject already exists to prevent exact duplicates
                            val existingSubjects = semesterManager.getSubjectsForSemester(semester.id)
                            val exists = existingSubjects.any { 
                                it.name == subjectName && it.credits == credits && it.grade == grade 
                            }
                            
                            if (!exists) {
                                val subject = Subject(
                                    name = subjectName,
                                    credits = credits,
                                    grade = grade,
                                    semesterId = semester.id
                                )
                                semesterManager.addSubject(semester.id, subject)
                                importedCount++
                            }
                        }
                    }
                }
            }
            
            if (!isParsingSubjects) {
                throw Exception("Invalid CSV format. Please use the downloaded template.")
            }
            
            Result.success(importedCount)
        } catch (e: Exception) {
            e.printStackTrace()
            Result.failure(e)
        }
    }

    private fun parseCsvLine(line: String): List<String> {
        val result = mutableListOf<String>()
        var currentToken = StringBuilder()
        var inQuotes = false
        
        for (char in line) {
            when {
                char == '\"' -> inQuotes = !inQuotes
                char == ',' && !inQuotes -> {
                    result.add(currentToken.toString())
                    currentToken = StringBuilder()
                }
                else -> currentToken.append(char)
            }
        }
        result.add(currentToken.toString())
        return result
    }
}
